application: sewpulse
version: live
runtime: go
api_version: go1

handlers:
- url: /faq
  static_files: templates/faq.html
  upload: templates/faq.html

- url: /static
  static_dir: static
  expiration: "1s"

- url: /.*
  script: _go_app
