application: sewpulse
version: live
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  expiration: "10d"

- url: /static
  static_dir: static
  expiration: "1s"

- url: /faq
  static_files: templates/faq.html
  upload: templates/faq.html
  login: admin

- url: /gzb/a/.*
  script: _go_app
  login: admin

- url: /gzb/a
  script: _go_app
  login: admin

- url: /rrk/a/.*
  script: _go_app
  login: admin

- url: /rrk/a
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: required
